### PR TITLE
Support JDK 11 and Tomcat 9

### PR DESCRIPTION
**Pull request by sharon-tickell**
Hi to the maintainers!

We have a platform that still uses this PID application, but which we need to be able to deploy into a runtime environment that involves JDK 11 and Tomcat 9.   This pull request is for the configuration tweaks we needed to make to get that to work, in case those would be of use by anyone else still using it.

As part of this PR, we've endeavored to replace the links to the now-vanished www.seegrid.csiro.au website pages with the best working equivalents we could find.   It does not look like the User Guide and API guide were migrated to Confluence along with the main website page, so we're depending on the Wayback machine for that content at the moment.

### CODE REVIEW

**Comment by ZakarFin** [comment]
Exactly what I was looking for but sadly it hasn't been merged. @sharon-tickell Do you have a fork for this that you are using? Looks like there's a couple of public forks to make it work with Tomcat 9.

**Comment by sharon-tickell** [comment]
@ZakarFin , snap - I was just reviewing where I was up to on this only today - must be that time of year or something.

My team's fork is at https://github.com/onaci/PID (specifically the `ereefs-dev` branch).

**Comment by ZakarFin** [comment]
Awesome! I'll take a look at it :)

**Comment by sharon-tickell** [comment]
@ZakarFin : actually, correct that branch name, please:   this PR  was made from the `platform_upgrade` branch(https://github.com/onaci/PID/tree/platform_upgrade) and is probably the best one to work from.   `ereefs-dev` is a work-in-progress and probably not stable.

**Comment by ZakarFin** [comment]
I added a fork for us here https://github.com/nlsfi/PID/tree/tomcat9 with your changes @sharon-tickell. We'll probably look into some other dependency updates as well and figure out some versioning with git tags and maven pom.xml etc to keep better track of what version is actually running on the servers.

**Comment by ZakarFin** [comment]
@sharon-tickell I don't have a better way of contacting so trying this way. FYI, I've just upgraded our version of the server code to work with Tomcat 10.1 and Java 21: https://github.com/nlsfi/PID/pull/11. I thought to use the restore functionality to bring in the mappings to my local db, but noticed that the restore functionality is actually implemented with a Flash-plugin that has probably been unsupported for some time now by any current browsers. Have you done anything to workaround the restore-functionality?

**Pull request closed without merging**
